---
- name: Copy Docker engine service file
  shell: sh install

- name: Enable and restart Docker engine
  systemd:
    name: docker
    daemon_reload: yes
    state: restarted
    enabled: yes
  register: started_docker
